FIND_PATH(XDR_INCLUDE_DIR xdr.h /usr/include/rpc /usr/local/include/rpc)

FIND_LIBRARY(XDR_LIBRARY NAMES rpcsvc PATH /usr/lib /usr/local/lib) 

IF (XDR_INCLUDE_DIR AND XDR_LIBRARY)
   SET(XDR_FOUND TRUE)
ENDIF (XDR_INCLUDE_DIR AND XDR_LIBRARY)


IF (XDR_FOUND)
   IF (NOT XDR_FIND_QUIETLY)
      MESSAGE(STATUS "Found xdr library: ${XDR_LIBRARY}")
   ENDIF (NOT XDR_FIND_QUIETLY)
ELSE (XDR_FOUND)
   IF (XDR_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find xdr library")
   ENDIF (XDR_FIND_REQUIRED)
ENDIF (XDR_FOUND)

